// <auto-generated />
using DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(BaseContext))]
    partial class BaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DataAccess.Entites.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Courses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Introduction to Computer Science"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Algorithms"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Calculus"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Physics"
                        });
                });

            modelBuilder.Entity("DataAccess.Entites.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BirthDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BirthDate");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Surname");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Students", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = "11/11/1960",
                            CourseId = 1,
                            Name = "Martin",
                            Surname = "Fowler"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = "12/12/1989",
                            CourseId = 2,
                            Name = "Jason",
                            Surname = "Taylor"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = "01/01/1984",
                            CourseId = 3,
                            Name = "Engin",
                            Surname = "Demirog"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = "03/12/1979",
                            CourseId = 4,
                            Name = "Bora",
                            Surname = "Kasmer"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = "04/12/1965",
                            CourseId = 4,
                            Name = "Mark",
                            Surname = "Price"
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = "05/12/1978",
                            CourseId = 2,
                            Name = "Robert",
                            Surname = "Martin"
                        });
                });

            modelBuilder.Entity("DataAccess.Entites.Student", b =>
                {
                    b.HasOne("DataAccess.Entites.Course", "Course")
                        .WithMany("Students")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("DataAccess.Entites.Course", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
